name: Deploy to AWS Lambda

# Trigger only on a push to the aws-lambda branch
on:
  push:
    branches:
      - aws-lambda
    tags-ignore:
      - '*'

jobs:

  deploy_layer:
    name: Deploy Lambda Layers
    runs-on: ubuntu-latest

    steps:

    # Configure AWS credentials for upload
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Clone tweetBot into the build environment
    - name: Download tweetBot
      uses: actions/checkout@v2
      with:
        repository: Jademalo/tweetBot
        path: tweetBot

    - name: Zip tweetBot and release to Layer
      run: |
        rm -r python
        mkdir python
        # Add tweetBot to the python folder
        cp -r tweetBot python/tweetBot
        # Zip the python folder
        zip --quiet -r python-tweetBot.zip python

        # Upload tweetBot to a Lambda Layer
        aws lambda publish-layer-version --layer-name python-tweetBot --zip-file fileb://python-tweetBot.zip --compatible-runtimes python3.6 python3.7 python3.8
