name: Deploy to Lambda Functions

# Trigger only on a push to the aws-lambda branch
on:
  push:
    branches:
      - aws-lambda
    tags-ignore:
      - '*'

jobs:
  deploy_genre:
    name: Deploy functions to Lambda
    runs-on: ubuntu-latest

    steps:

      # Clone the project into the build environment
      - name: Clone Project
        uses: actions/checkout@v1
        with:
          fetch-depth: 50
          submodules: true

      # Zip the project ready for deployment
      - name: Zip Project
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r ./bundle.zip ./

      # Deploy the function for Genre Defining
      - name: Deploy Genre Defining Function
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: jadeBots-genre-post
          description: 'The function to post to Genre Defining'
          runtime: python3.8
          handler: lambda.awsRunGenre
          zip_file: bundle.zip
          dry_run: true

      # Deploy the function for Mario Variants
      - name: Deploy Mario Variants Function
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: jadeBots-mario-post
          description: 'The function to post to Mario Variants'
          runtime: python3.8
          handler: lambda.awsRunMario
          zip_file: bundle.zip
          dry_run: true

      # Deploy the function for Romantics Ebooks
      - name: Deploy Romantics Ebooks Function
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: jadeBots-romantics-post
          description: 'The function to post to Genre Defining'
          runtime: python3.8
          handler: lambda.awsRunRomantics
          zip_file: bundle.zip
          dry_run: true

      # Deploy the function for Ulysses Ebooks
      - name: Deploy Ulysses Ebooks Function
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: jadeBots-ulysses-post
          description: 'The function to post to Ulysses Ebooks'
          runtime: python3.8
          handler: lambda.awsRunUlysses
          zip_file: bundle.zip
          dry_run: true
